# Generated by Django 5.1.1 on 2025-01-14 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serpiente',
            fields=[
                ('idSerpiente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre3', models.CharField(max_length=45)),
                ('nombreCientifico', models.CharField(max_length=100)),
                ('reino', models.CharField(max_length=45)),
                ('especie', models.CharField(max_length=45)),
                ('clase', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=45)),
                ('familia', models.CharField(max_length=45)),
                ('imagen', models.CharField(max_length=200, null=True)),
                ('venenosa', models.BooleanField()),
                ('descripcion', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(max_length=200, null=True)),
                ('correo', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_n', models.CharField(max_length=45)),
                ('rol', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=300, null=True)),
                ('imagen_fonodo', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idReporte', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('imagen', models.CharField(max_length=200)),
                ('serpientes_id_serpientes', models.ForeignKey(db_column='serpientes_id_serpientes', null=True, on_delete=django.db.models.deletion.CASCADE, to='snake_meta.serpiente')),
                ('usuario_id_usuario', models.ForeignKey(db_column='usuario_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='snake_meta.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Georeferencia',
            fields=[
                ('idGeoreferencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=20)),
                ('zona', models.CharField(max_length=100)),
                ('coordenadas', models.CharField(max_length=200)),
                ('serpientes_id_serpientes', models.ForeignKey(db_column='serpientes_id_serpientes', on_delete=django.db.models.deletion.CASCADE, to='snake_meta.serpiente')),
                ('usuario_id_usuario', models.ForeignKey(db_column='usuario_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='snake_meta.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=1000)),
                ('reporte_id_reporte', models.ForeignKey(db_column='reporte_id_reporte', on_delete=django.db.models.deletion.CASCADE, to='snake_meta.reporte')),
                ('usuario_id_usuario', models.ForeignKey(db_column='usuario_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='snake_meta.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
